stages:
  - checks
  - build
  - test
  - harvey-dcb
  - k-dcb

markdown-link-check:
  stage: checks
  when: manual
  tags:
    - compdam-h
  script:
    - python "$CI_PROJECT_DIR/utilities/link-checker/check_markdown_links.py" "$CI_PROJECT_DIR"

#region build stage, harvey
h-abq2023-build:
  stage: build
  when: manual
  tags:
    - compdam-h
  script:
    - cd "$CI_BUILDS_DIR"
    - "$CI_BUILDS_DIR/call_setup_py.sh $CI_PROJECT_DIR"
    - cp "$CI_PROJECT_DIR/tests/abaqus_v6.env" "$CI_BUILDS_DIR/abaqus_v6.env"
    - mkdir -p "$CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2023.HF5"
    - "$CI_BUILDS_DIR/compile_abq2023.sh $CI_PROJECT_DIR/for/CompDam_DGD.for $CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2023.HF5"

h-abq2024-build:
  stage: build
  when: manual
  tags:
    - compdam-h
  script:
    - cd "$CI_BUILDS_DIR"
    - "$CI_BUILDS_DIR/call_setup_py.sh $CI_PROJECT_DIR"
    - cp "$CI_PROJECT_DIR/tests/abaqus_v6.env" "$CI_BUILDS_DIR/abaqus_v6.env"
    - mkdir -p "$CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2024"
    - "$CI_BUILDS_DIR/compile_abq2024.sh $CI_PROJECT_DIR/for/CompDam_DGD.for $CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2024"
#endregion

#region build stage, k
k-abq2020-build:
  stage: build
  when: manual
  tags:
    - compdam-k
  script:
    - cd "$CI_BUILDS_DIR"
    - "$CI_BUILDS_DIR/call_setup_py.sh $CI_PROJECT_DIR"
    - cp "$CI_PROJECT_DIR/tests/abaqus_v6.env" "$CI_BUILDS_DIR/abaqus_v6.env"
    - "$CI_BUILDS_DIR/compile_abq.sh 2020 $CI_PROJECT_DIR/for/CompDam_DGD.for $CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2020"

k-abq2021-build:
  stage: build
  when: manual
  tags:
    - compdam-k
  script:
    - cd "$CI_BUILDS_DIR"
    - "$CI_BUILDS_DIR/call_setup_py.sh $CI_PROJECT_DIR"
    - cp "$CI_PROJECT_DIR/tests/abaqus_v6.env" "$CI_BUILDS_DIR/abaqus_v6.env"
    - "$CI_BUILDS_DIR/compile_abq.sh 2021 $CI_PROJECT_DIR/for/CompDam_DGD.for $CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2021"

k-abq2022-build:
  stage: build
  when: manual
  tags:
    - compdam-k
  script:
    - cd "$CI_BUILDS_DIR"
    - "$CI_BUILDS_DIR/call_setup_py.sh $CI_PROJECT_DIR"
    - cp "$CI_PROJECT_DIR/tests/abaqus_v6.env" "$CI_BUILDS_DIR/abaqus_v6.env"
    - "$CI_BUILDS_DIR/compile_abq.sh 2022 $CI_PROJECT_DIR/for/CompDam_DGD.for $CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2022"

k-abq2023-build:
  stage: build
  when: manual
  tags:
    - compdam-k
  script:
    - cd "$CI_BUILDS_DIR"
    - "$CI_BUILDS_DIR/call_setup_py.sh $CI_PROJECT_DIR"
    - cp "$CI_PROJECT_DIR/tests/abaqus_v6.env" "$CI_BUILDS_DIR/abaqus_v6.env"
    - "$CI_BUILDS_DIR/compile_abq.sh 2023 $CI_PROJECT_DIR/for/CompDam_DGD.for $CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2023"

k-abq2024-build:
  stage: build
  when: manual
  tags:
    - compdam-k
  script:
    - cd "$CI_BUILDS_DIR"
    - "$CI_BUILDS_DIR/call_setup_py.sh $CI_PROJECT_DIR"
    - cp "$CI_PROJECT_DIR/tests/abaqus_v6.env" "$CI_BUILDS_DIR/abaqus_v6.env"
    - "$CI_BUILDS_DIR/compile_abq.sh 2024 $CI_PROJECT_DIR/for/CompDam_DGD.for $CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2024"

k-abq2025-build:
  stage: build
  when: manual
  tags:
    - compdam-k
  script:
    - cd "$CI_BUILDS_DIR"
    - "$CI_BUILDS_DIR/call_setup_py.sh $CI_PROJECT_DIR"
    - cp "$CI_PROJECT_DIR/tests/abaqus_v6.env" "$CI_BUILDS_DIR/abaqus_v6.env"
    - "$CI_BUILDS_DIR/compile_abq.sh 2025 $CI_PROJECT_DIR/for/CompDam_DGD.for $CI_BUILDS_DIR/CompDam_DGD_$CI_COMMIT_SHORT_SHA/Abaqus_2025"
#endregion

#region test stage, harvey
h-abq2023-tests:
  stage: test
  when: manual
  tags:
    - compdam-h
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA tests/test_runner.py"

h-abq2024-tests:
  stage: test
  when: manual
  tags:
    - compdam-h
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA tests/test_runner.py"
#endregion

#region test stage, k
k-abq2020-tests:
  stage: test
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2020 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA tests/test_runner.py"

k-abq2021-tests:
  stage: test
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA tests/test_runner.py"

k-abq2022-tests:
  stage: test
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA tests/test_runner.py"

k-abq2023-tests:
  stage: test
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA tests/test_runner.py"

k-abq2024-tests:
  stage: test
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA tests/test_runner.py"

k-abq2025-tests:
  stage: test
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA tests/test_runner.py"
#endregion

#region examples, harvey-dcb
abq2024-dcb-quasi-static-h:
  stage: harvey-dcb
  when: manual
  tags:
    - compdam-h
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStatic 15"

abq2024-dcb-quasi-static-insert-h:
  stage: harvey-dcb
  when: manual
  tags:
    - compdam-h
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStaticInsert 15"

abq2024-dcb-large-h:
  stage: harvey-dcb
  when: manual
  tags:
    - compdam-h
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_narrow 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 40"

abq2024-dcb-dynamic-h:
  stage: harvey-dcb
  when: manual
  tags:
    - compdam-h
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBDynamic 15"

abq2024-dcb-fatigue-h:
  stage: harvey-dcb
  when: manual
  tags:
    - compdam-h
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBFatigue 15"
#endregion

#region examples, k-dcb
#region 2021
abq2021-dcb-quasi-static-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStatic 15"

abq2021-dcb-quasi-static-insert-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStaticInsert 15"

abq2021-dcb-large-all-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_narrow 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 40"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2021-dcb-large-80-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2021-dcb-dynamic-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBDynamic 15"

abq2021-dcb-fatigue-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2021 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBFatigue 15"
#endregion

#region 2022
abq2022-dcb-quasi-static-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStatic 15"

abq2022-dcb-quasi-static-insert-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStaticInsert 15"

abq2022-dcb-large-all-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_narrow 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 40"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2022-dcb-large-80-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2022-dcb-dynamic-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBDynamic 15"

abq2022-dcb-fatigue-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2022 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBFatigue 15"
#endregion

#region 2023
abq2023-dcb-quasi-static-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStatic 15"

abq2023-dcb-quasi-static-insert-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStaticInsert 15"

abq2023-dcb-large-all-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_narrow 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 40"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2023-dcb-large-80-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2023-dcb-dynamic-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBDynamic 15"

abq2023-dcb-fatigue-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2023 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBFatigue 15"
#endregion

#region 2024
abq2024-dcb-quasi-static-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStatic 15"

abq2024-dcb-quasi-static-insert-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStaticInsert 15"

abq2024-dcb-large-all-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_narrow 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 40"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2024-dcb-large-80-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2024-dcb-dynamic-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBDynamic 15"

abq2024-dcb-fatigue-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2024 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBFatigue 15"
#endregion

#region 2025
abq2025-dcb-quasi-static-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStatic 15"

abq2025-dcb-quasi-static-insert-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBQuasiStaticInsert 15"

abq2025-dcb-large-all-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_narrow 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 15"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 40"
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2025-dcb-large-80-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBLarge.test_DCB_3D_compdam_multimaterial_wide 80"

abq2025-dcb-dynamic-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBDynamic 15"

abq2025-dcb-fatigue-k:
  stage: k-dcb
  when: manual
  tags:
    - compdam-k
  script:
    - "$CI_BUILDS_DIR/run_automatic_tests.sh 2025 $CI_BUILDS_DIR $CI_PROJECT_DIR $CI_COMMIT_SHORT_SHA examples/interlaminar/dcb_runner.py DCBFatigue 15"
#endregion
#endregion
